# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{the-perfect-gem}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Nichols"]
  s.date = %q{2011-05-07}
  s.description = %q{TODO}
  s.email = %q{josh@technicalpickles.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".yardoc/checksums",
    ".yardoc/objects/root.dat",
    ".yardoc/proxy_types",
    "History.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "doc/Strut.html",
    "doc/Strut/Controller.html",
    "doc/Strut/Controller/Action.html",
    "doc/Strut/Controller/ClassMethods.html",
    "doc/Strut/Controller/Filter.html",
    "doc/Strut/Controller/Filter/ClassMethods.html",
    "doc/Strut/Controller/Respond.html",
    "doc/Strut/Model.html",
    "doc/Strut/Model/Action.html",
    "doc/Strut/Model/Holder.html",
    "doc/_index.html",
    "doc/class_list.html",
    "doc/css/common.css",
    "doc/css/full_list.css",
    "doc/css/style.css",
    "doc/file.README.html",
    "doc/file_list.html",
    "doc/frames.html",
    "doc/index.html",
    "doc/js/app.js",
    "doc/js/full_list.js",
    "doc/js/jquery.js",
    "doc/method_list.html",
    "doc/top-level-namespace.html",
    "lib/strut.rb",
    "lib/strut/controller.rb",
    "lib/strut/controller/action.rb",
    "lib/strut/controller/filter.rb",
    "lib/strut/controller/respond.rb",
    "lib/strut/model/action.rb",
    "lib/strut/model/holder.rb",
    "log/development.log",
    "pkg/strut-0.0.1.gem",
    "pkg/strut-0.0.1.tgz",
    "pkg/strut-0.0.1/.gemtest",
    "pkg/strut-0.0.1/History.txt",
    "pkg/strut-0.0.1/Manifest.txt",
    "pkg/strut-0.0.1/PostInstall.txt",
    "pkg/strut-0.0.1/README.rdoc",
    "pkg/strut-0.0.1/Rakefile",
    "pkg/strut-0.0.1/lib/strut.rb",
    "pkg/strut-0.0.1/script/console",
    "pkg/strut-0.0.1/script/destroy",
    "pkg/strut-0.0.1/script/generate",
    "pkg/strut-0.0.2.gem",
    "pkg/strut-0.0.2.tgz",
    "pkg/strut-0.0.2/.gemtest",
    "pkg/strut-0.0.2/History.txt",
    "pkg/strut-0.0.2/Manifest.txt",
    "pkg/strut-0.0.2/PostInstall.txt",
    "pkg/strut-0.0.2/README.rdoc",
    "pkg/strut-0.0.2/Rakefile",
    "pkg/strut-0.0.2/lib/strut.rb",
    "pkg/strut-0.0.2/lib/strut/controller.rb",
    "pkg/strut-0.0.2/lib/strut/controller/action.rb",
    "pkg/strut-0.0.2/lib/strut/controller/filter.rb",
    "pkg/strut-0.0.2/lib/strut/controller/respond.rb",
    "pkg/strut-0.0.2/lib/strut/model/action.rb",
    "pkg/strut-0.0.2/lib/strut/model/holder.rb",
    "pkg/strut-0.0.2/script/console",
    "pkg/strut-0.0.2/script/destroy",
    "pkg/strut-0.0.2/script/generate",
    "script/console",
    "script/destroy",
    "script/generate",
    "spec/controller/respond_spec.rb",
    "spec/controller_spec.rb",
    "spec/fake_app.rb",
    "spec/model/action_spec.rb",
    "spec/model/holder_spec.rb",
    "spec/spec_helper.rb",
    "spec/strut_spec.rb"
  ]
  s.homepage = %q{http://github.com/technicalpickles/the-perfect-gem}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.1}
  s.summary = %q{TODO}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

